// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_true`, `generate_proof_string_for_format`, `get_active_did_internal`, `get_active_identity_sync`, `load_oauth_links`, `save_oauth_links`, `storage_path`, `update_device_manifest`, `verify_raw_sig`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProfileMetadata`, `UserIdentity`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<DeviceManifest> getDeviceManifest() =>
    RustLib.instance.api.crateApiIdentityGetDeviceManifest();

Future<void> saveDeviceManifest({required DeviceManifest manifest}) =>
    RustLib.instance.api.crateApiIdentitySaveDeviceManifest(manifest: manifest);

/// Closes the active databases, unloads identity, and signals network shutdown
Future<void> signOutProfile() =>
    RustLib.instance.api.crateApiIdentitySignOutProfile();

/// Sets the given DID as the active profile and boots up its P2P network node.
Future<bool> switchActiveProfile({required String did}) =>
    RustLib.instance.api.crateApiIdentitySwitchActiveProfile(did: did);

/// Generates a genuine ed25519 keypair and encodes it into a did:peer identifier.
/// This is the initialization of a session. By generating keys
/// locally on the device's CSPRNG (OsRng), we ensure that no central
/// authority ever sees the private secret, fulfilling the data ownership mandate.
Future<IdentityVault> generateNewIdentity() =>
    RustLib.instance.api.crateApiIdentityGenerateNewIdentity();

/// Returns the active node identity. Returns an empty vault if no identity is active.
Future<IdentityVault> getActiveIdentity() =>
    RustLib.instance.api.crateApiIdentityGetActiveIdentity();

Future<IdentityVault> updateActiveProfile({
  required String name,
  required String avatar,
}) => RustLib.instance.api.crateApiIdentityUpdateActiveProfile(
  name: name,
  avatar: avatar,
);

/// Generates a signed proof string linking the display name to the did:peer key.
/// Format (Legacy): exotalk-proof:v1:did={DID}:name={NAME}:sig={BASE58_SIG}
/// Format (Full Compact): etp1:{PUBKEY_B58}.{SIG_B58}
/// Format (Minimal): ets1:{SIG_B58}
Future<String> generateVerificationProof({required String format}) => RustLib
    .instance
    .api
    .crateApiIdentityGenerateVerificationProof(format: format);

/// Evaluates all available proof formats and returns the best one that fits within max_chars.
Future<String> generateBestProof({required BigInt maxChars}) =>
    RustLib.instance.api.crateApiIdentityGenerateBestProof(maxChars: maxChars);

/// Verifies any supported ExoTalk proof string locally.
Future<bool> verifyProofLocally({required String proof}) =>
    RustLib.instance.api.crateApiIdentityVerifyProofLocally(proof: proof);

Future<IdentityVault> setIngressEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiIdentitySetIngressEnabled(enabled: enabled);

Future<IdentityVault> setEgressEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiIdentitySetEgressEnabled(enabled: enabled);

/// Adds a pending (unverified) link to the vault.
Future<IdentityVault> addVerificationLink({
  required String label,
  required String url,
}) => RustLib.instance.api.crateApiIdentityAddVerificationLink(
  label: label,
  url: url,
);

/// Marks an existing link by URL as verified or failed after an HTTP check.
Future<IdentityVault> confirmVerificationLink({
  required String url,
  required bool verified,
}) => RustLib.instance.api.crateApiIdentityConfirmVerificationLink(
  url: url,
  verified: verified,
);

/// Removes a link by URL.
Future<IdentityVault> removeVerificationLink({required String url}) =>
    RustLib.instance.api.crateApiIdentityRemoveVerificationLink(url: url);

/// Renames the display label of a link.
Future<IdentityVault> updateLinkLabel({
  required String url,
  required String newLabel,
}) => RustLib.instance.api.crateApiIdentityUpdateLinkLabel(
  url: url,
  newLabel: newLabel,
);

/// Returns the full name history list.
Future<List<NameRecord>> getNameHistory() =>
    RustLib.instance.api.crateApiIdentityGetNameHistory();

/// Links an OAuth account to the active did:peer by signing a binding proof.
Future<OAuthLink> addOauthLink({
  required String provider,
  required String displayName,
  required String sub,
}) => RustLib.instance.api.crateApiIdentityAddOauthLink(
  provider: provider,
  displayName: displayName,
  sub: sub,
);

/// Removes an OAuth link by provider key.
Future<void> removeOauthLink({required String provider}) =>
    RustLib.instance.api.crateApiIdentityRemoveOauthLink(provider: provider);

/// Returns all linked OAuth accounts.
Future<List<OAuthLink>> getOauthLinks() =>
    RustLib.instance.api.crateApiIdentityGetOauthLinks();

/// Finds the did:peer for a given OAuth provider + sub combination.
/// Returns an empty string if not found.
Future<String> findDidForOauth({
  required String provider,
  required String sub,
}) => RustLib.instance.api.crateApiIdentityFindDidForOauth(
  provider: provider,
  sub: sub,
);

/// Generates a short-lived signed pairing token for QR-code device sync.
/// The token encodes: did + timestamp + signature. Expires after 5 minutes.
Future<String> generateDevicePairingToken() =>
    RustLib.instance.api.crateApiIdentityGenerateDevicePairingToken();

/// Verifies a pairing token (checks signature and 5-minute expiry).
Future<bool> verifyDevicePairingToken({required String token}) =>
    RustLib.instance.api.crateApiIdentityVerifyDevicePairingToken(token: token);

/// Exports the full profile + OAuth links as a JSON string (for cross-device transfer).
/// In a production implementation this would be encrypted; here it is signed.
Future<String> exportProfileBundle() =>
    RustLib.instance.api.crateApiIdentityExportProfileBundle();

/// Imports a profile bundle from another device (verifies did:peer signature first).
Future<bool> importProfileBundle({required String bundle}) =>
    RustLib.instance.api.crateApiIdentityImportProfileBundle(bundle: bundle);

Future<String?> findProfileByOauth({
  required String provider,
  required String sub,
}) => RustLib.instance.api.crateApiIdentityFindProfileByOauth(
  provider: provider,
  sub: sub,
);

Future<String> createProfileFromOauth({
  required String provider,
  required String sub,
  required String name,
  required String avatar,
}) => RustLib.instance.api.crateApiIdentityCreateProfileFromOauth(
  provider: provider,
  sub: sub,
  name: name,
  avatar: avatar,
);

Future<bool> linkOauthToExistingProfile({
  required String did,
  required String provider,
  required String sub,
}) => RustLib.instance.api.crateApiIdentityLinkOauthToExistingProfile(
  did: did,
  provider: provider,
  sub: sub,
);

/// Core device settings and manifest of all local profiles.
class DeviceManifest {
  final String tenancyMode;
  final List<ProfileRecord> profiles;
  final String? associatedConsciaId;

  const DeviceManifest({
    required this.tenancyMode,
    required this.profiles,
    this.associatedConsciaId,
  });

  @override
  int get hashCode =>
      tenancyMode.hashCode ^ profiles.hashCode ^ associatedConsciaId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceManifest &&
          runtimeType == other.runtimeType &&
          tenancyMode == other.tenancyMode &&
          profiles == other.profiles &&
          associatedConsciaId == other.associatedConsciaId;
}

/// Represents a loaded Node Identity (Keypair).
/// This structure represents the user's presence in the mesh.
/// It contains the local root secret (ed25519) from which all sub-capabilities
/// and message signatures are derived.
class IdentityVault {
  final String did;
  final String secret;
  final String displayName;
  final String avatarUrl;
  final String proofString;
  final List<VerifiedLink> verifiedLinks;
  final List<OAuthLink> oauthLinks;
  final List<NameRecord> nameHistory;
  final bool ingressEnabled;
  final bool egressEnabled;

  const IdentityVault({
    required this.did,
    required this.secret,
    required this.displayName,
    required this.avatarUrl,
    required this.proofString,
    required this.verifiedLinks,
    required this.oauthLinks,
    required this.nameHistory,
    required this.ingressEnabled,
    required this.egressEnabled,
  });

  @override
  int get hashCode =>
      did.hashCode ^
      secret.hashCode ^
      displayName.hashCode ^
      avatarUrl.hashCode ^
      proofString.hashCode ^
      verifiedLinks.hashCode ^
      oauthLinks.hashCode ^
      nameHistory.hashCode ^
      ingressEnabled.hashCode ^
      egressEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityVault &&
          runtimeType == other.runtimeType &&
          did == other.did &&
          secret == other.secret &&
          displayName == other.displayName &&
          avatarUrl == other.avatarUrl &&
          proofString == other.proofString &&
          verifiedLinks == other.verifiedLinks &&
          oauthLinks == other.oauthLinks &&
          nameHistory == other.nameHistory &&
          ingressEnabled == other.ingressEnabled &&
          egressEnabled == other.egressEnabled;
}

/// An archived name record kept when the user renames themselves.
class NameRecord {
  final String name;
  final String proofString;
  final List<VerifiedLink> verifiedLinks;
  final PlatformInt64 activeFromMs;
  final PlatformInt64 retiredAtMs;
  final String changeCertificate;

  const NameRecord({
    required this.name,
    required this.proofString,
    required this.verifiedLinks,
    required this.activeFromMs,
    required this.retiredAtMs,
    required this.changeCertificate,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      proofString.hashCode ^
      verifiedLinks.hashCode ^
      activeFromMs.hashCode ^
      retiredAtMs.hashCode ^
      changeCertificate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NameRecord &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          proofString == other.proofString &&
          verifiedLinks == other.verifiedLinks &&
          activeFromMs == other.activeFromMs &&
          retiredAtMs == other.retiredAtMs &&
          changeCertificate == other.changeCertificate;
}

/// An OAuth account linked as a secondary sign-in method.
class OAuthLink {
  final String provider;
  final String displayName;
  final String sub;
  final String bindingProof;
  final PlatformInt64 linkedAtMs;

  const OAuthLink({
    required this.provider,
    required this.displayName,
    required this.sub,
    required this.bindingProof,
    required this.linkedAtMs,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      displayName.hashCode ^
      sub.hashCode ^
      bindingProof.hashCode ^
      linkedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OAuthLink &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          displayName == other.displayName &&
          sub == other.sub &&
          bindingProof == other.bindingProof &&
          linkedAtMs == other.linkedAtMs;
}

class ProfileRecord {
  final String did;
  final String displayName;
  final String avatarUrl;
  final List<String> oauthSubs;

  const ProfileRecord({
    required this.did,
    required this.displayName,
    required this.avatarUrl,
    required this.oauthSubs,
  });

  @override
  int get hashCode =>
      did.hashCode ^
      displayName.hashCode ^
      avatarUrl.hashCode ^
      oauthSubs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileRecord &&
          runtimeType == other.runtimeType &&
          did == other.did &&
          displayName == other.displayName &&
          avatarUrl == other.avatarUrl &&
          oauthSubs == other.oauthSubs;
}

/// An independently-verified link between a did:peer and a public URL.
class VerifiedLink {
  final String platformLabel;
  final String url;
  final bool isVerified;
  final PlatformInt64 verifiedAtMs;

  const VerifiedLink({
    required this.platformLabel,
    required this.url,
    required this.isVerified,
    required this.verifiedAtMs,
  });

  static Future<VerifiedLink> default_() =>
      RustLib.instance.api.crateApiIdentityVerifiedLinkDefault();

  @override
  int get hashCode =>
      platformLabel.hashCode ^
      url.hashCode ^
      isVerified.hashCode ^
      verifiedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerifiedLink &&
          runtimeType == other.runtimeType &&
          platformLabel == other.platformLabel &&
          url == other.url &&
          isVerified == other.isVerified &&
          verifiedAtMs == other.verifiedAtMs;
}
