section: screens
    Exocracy:
    Exonomy:
end

section: links
    Exocracy:
        up = Exonomy
    Exonomy:
        down = Exocracy
end

section: options
    relativeMouseMoves = false
    screenSaverSync = true
    win32KeepForeground = false
    clipboardSharing = true
    switchCorners = none 
    switchCornerSize = 0
end
