// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/identity.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1311409940;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'exoauth_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<OAuthLink> crateApiIdentityAddOauthLink({
    required String provider,
    required String displayName,
    required String sub,
  });

  Future<IdentityVault> crateApiIdentityAddVerificationLink({
    required String label,
    required String url,
  });

  Future<IdentityVault> crateApiIdentityConfirmVerificationLink({
    required String url,
    required bool verified,
  });

  Future<String> crateApiIdentityCreateProfileFromOauth({
    required String provider,
    required String sub,
    required String name,
    required String avatar,
  });

  Future<String> crateApiIdentityExportProfileBundle();

  Future<String> crateApiIdentityFindDidForOauth({
    required String provider,
    required String sub,
  });

  Future<String?> crateApiIdentityFindProfileByOauth({
    required String provider,
    required String sub,
  });

  Future<String> crateApiIdentityGenerateBestProof({required BigInt maxChars});

  Future<String> crateApiIdentityGenerateDevicePairingToken();

  Future<IdentityVault> crateApiIdentityGenerateNewIdentity();

  Future<String> crateApiIdentityGenerateVerificationProof({
    required String format,
  });

  Future<IdentityVault> crateApiIdentityGetActiveIdentity();

  Future<DeviceManifest> crateApiIdentityGetDeviceManifest();

  Future<List<NameRecord>> crateApiIdentityGetNameHistory();

  Future<List<OAuthLink>> crateApiIdentityGetOauthLinks();

  Future<bool> crateApiIdentityImportProfileBundle({required String bundle});

  Future<bool> crateApiIdentityLinkOauthToExistingProfile({
    required String did,
    required String provider,
    required String sub,
  });

  Future<void> crateApiIdentityRemoveOauthLink({required String provider});

  Future<IdentityVault> crateApiIdentityRemoveVerificationLink({
    required String url,
  });

  Future<void> crateApiIdentitySaveDeviceManifest({
    required DeviceManifest manifest,
  });

  Future<IdentityVault> crateApiIdentitySetEgressEnabled({
    required bool enabled,
  });

  Future<IdentityVault> crateApiIdentitySetIngressEnabled({
    required bool enabled,
  });

  Future<void> crateApiIdentitySignOutProfile();

  Future<bool> crateApiIdentitySwitchActiveProfile({required String did});

  Future<IdentityVault> crateApiIdentityUpdateActiveProfile({
    required String name,
    required String avatar,
  });

  Future<IdentityVault> crateApiIdentityUpdateLinkLabel({
    required String url,
    required String newLabel,
  });

  Future<VerifiedLink> crateApiIdentityVerifiedLinkDefault();

  Future<bool> crateApiIdentityVerifyDevicePairingToken({
    required String token,
  });

  Future<bool> crateApiIdentityVerifyProofLocally({required String proof});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<OAuthLink> crateApiIdentityAddOauthLink({
    required String provider,
    required String displayName,
    required String sub,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(provider, serializer);
          sse_encode_String(displayName, serializer);
          sse_encode_String(sub, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_o_auth_link,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityAddOauthLinkConstMeta,
        argValues: [provider, displayName, sub],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityAddOauthLinkConstMeta =>
      const TaskConstMeta(
        debugName: "add_oauth_link",
        argNames: ["provider", "displayName", "sub"],
      );

  @override
  Future<IdentityVault> crateApiIdentityAddVerificationLink({
    required String label,
    required String url,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(label, serializer);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_vault,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityAddVerificationLinkConstMeta,
        argValues: [label, url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityAddVerificationLinkConstMeta =>
      const TaskConstMeta(
        debugName: "add_verification_link",
        argNames: ["label", "url"],
      );

  @override
  Future<IdentityVault> crateApiIdentityConfirmVerificationLink({
    required String url,
    required bool verified,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_bool(verified, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_vault,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityConfirmVerificationLinkConstMeta,
        argValues: [url, verified],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityConfirmVerificationLinkConstMeta =>
      const TaskConstMeta(
        debugName: "confirm_verification_link",
        argNames: ["url", "verified"],
      );

  @override
  Future<String> crateApiIdentityCreateProfileFromOauth({
    required String provider,
    required String sub,
    required String name,
    required String avatar,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(provider, serializer);
          sse_encode_String(sub, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(avatar, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityCreateProfileFromOauthConstMeta,
        argValues: [provider, sub, name, avatar],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityCreateProfileFromOauthConstMeta =>
      const TaskConstMeta(
        debugName: "create_profile_from_oauth",
        argNames: ["provider", "sub", "name", "avatar"],
      );

  @override
  Future<String> crateApiIdentityExportProfileBundle() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityExportProfileBundleConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityExportProfileBundleConstMeta =>
      const TaskConstMeta(debugName: "export_profile_bundle", argNames: []);

  @override
  Future<String> crateApiIdentityFindDidForOauth({
    required String provider,
    required String sub,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(provider, serializer);
          sse_encode_String(sub, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityFindDidForOauthConstMeta,
        argValues: [provider, sub],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityFindDidForOauthConstMeta =>
      const TaskConstMeta(
        debugName: "find_did_for_oauth",
        argNames: ["provider", "sub"],
      );

  @override
  Future<String?> crateApiIdentityFindProfileByOauth({
    required String provider,
    required String sub,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(provider, serializer);
          sse_encode_String(sub, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityFindProfileByOauthConstMeta,
        argValues: [provider, sub],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityFindProfileByOauthConstMeta =>
      const TaskConstMeta(
        debugName: "find_profile_by_oauth",
        argNames: ["provider", "sub"],
      );

  @override
  Future<String> crateApiIdentityGenerateBestProof({required BigInt maxChars}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_usize(maxChars, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityGenerateBestProofConstMeta,
        argValues: [maxChars],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityGenerateBestProofConstMeta =>
      const TaskConstMeta(
        debugName: "generate_best_proof",
        argNames: ["maxChars"],
      );

  @override
  Future<String> crateApiIdentityGenerateDevicePairingToken() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityGenerateDevicePairingTokenConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityGenerateDevicePairingTokenConstMeta =>
      const TaskConstMeta(
        debugName: "generate_device_pairing_token",
        argNames: [],
      );

  @override
  Future<IdentityVault> crateApiIdentityGenerateNewIdentity() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_vault,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityGenerateNewIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityGenerateNewIdentityConstMeta =>
      const TaskConstMeta(debugName: "generate_new_identity", argNames: []);

  @override
  Future<String> crateApiIdentityGenerateVerificationProof({
    required String format,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(format, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityGenerateVerificationProofConstMeta,
        argValues: [format],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityGenerateVerificationProofConstMeta =>
      const TaskConstMeta(
        debugName: "generate_verification_proof",
        argNames: ["format"],
      );

  @override
  Future<IdentityVault> crateApiIdentityGetActiveIdentity() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_vault,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityGetActiveIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityGetActiveIdentityConstMeta =>
      const TaskConstMeta(debugName: "get_active_identity", argNames: []);

  @override
  Future<DeviceManifest> crateApiIdentityGetDeviceManifest() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_manifest,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityGetDeviceManifestConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityGetDeviceManifestConstMeta =>
      const TaskConstMeta(debugName: "get_device_manifest", argNames: []);

  @override
  Future<List<NameRecord>> crateApiIdentityGetNameHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_name_record,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityGetNameHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityGetNameHistoryConstMeta =>
      const TaskConstMeta(debugName: "get_name_history", argNames: []);

  @override
  Future<List<OAuthLink>> crateApiIdentityGetOauthLinks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_o_auth_link,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityGetOauthLinksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityGetOauthLinksConstMeta =>
      const TaskConstMeta(debugName: "get_oauth_links", argNames: []);

  @override
  Future<bool> crateApiIdentityImportProfileBundle({required String bundle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(bundle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityImportProfileBundleConstMeta,
        argValues: [bundle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityImportProfileBundleConstMeta =>
      const TaskConstMeta(
        debugName: "import_profile_bundle",
        argNames: ["bundle"],
      );

  @override
  Future<bool> crateApiIdentityLinkOauthToExistingProfile({
    required String did,
    required String provider,
    required String sub,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(did, serializer);
          sse_encode_String(provider, serializer);
          sse_encode_String(sub, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityLinkOauthToExistingProfileConstMeta,
        argValues: [did, provider, sub],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityLinkOauthToExistingProfileConstMeta =>
      const TaskConstMeta(
        debugName: "link_oauth_to_existing_profile",
        argNames: ["did", "provider", "sub"],
      );

  @override
  Future<void> crateApiIdentityRemoveOauthLink({required String provider}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(provider, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityRemoveOauthLinkConstMeta,
        argValues: [provider],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityRemoveOauthLinkConstMeta =>
      const TaskConstMeta(
        debugName: "remove_oauth_link",
        argNames: ["provider"],
      );

  @override
  Future<IdentityVault> crateApiIdentityRemoveVerificationLink({
    required String url,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_vault,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityRemoveVerificationLinkConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityRemoveVerificationLinkConstMeta =>
      const TaskConstMeta(
        debugName: "remove_verification_link",
        argNames: ["url"],
      );

  @override
  Future<void> crateApiIdentitySaveDeviceManifest({
    required DeviceManifest manifest,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_device_manifest(manifest, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentitySaveDeviceManifestConstMeta,
        argValues: [manifest],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentitySaveDeviceManifestConstMeta =>
      const TaskConstMeta(
        debugName: "save_device_manifest",
        argNames: ["manifest"],
      );

  @override
  Future<IdentityVault> crateApiIdentitySetEgressEnabled({
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_vault,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentitySetEgressEnabledConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentitySetEgressEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "set_egress_enabled",
        argNames: ["enabled"],
      );

  @override
  Future<IdentityVault> crateApiIdentitySetIngressEnabled({
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_vault,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentitySetIngressEnabledConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentitySetIngressEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "set_ingress_enabled",
        argNames: ["enabled"],
      );

  @override
  Future<void> crateApiIdentitySignOutProfile() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentitySignOutProfileConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentitySignOutProfileConstMeta =>
      const TaskConstMeta(debugName: "sign_out_profile", argNames: []);

  @override
  Future<bool> crateApiIdentitySwitchActiveProfile({required String did}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(did, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentitySwitchActiveProfileConstMeta,
        argValues: [did],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentitySwitchActiveProfileConstMeta =>
      const TaskConstMeta(
        debugName: "switch_active_profile",
        argNames: ["did"],
      );

  @override
  Future<IdentityVault> crateApiIdentityUpdateActiveProfile({
    required String name,
    required String avatar,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(avatar, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_vault,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityUpdateActiveProfileConstMeta,
        argValues: [name, avatar],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityUpdateActiveProfileConstMeta =>
      const TaskConstMeta(
        debugName: "update_active_profile",
        argNames: ["name", "avatar"],
      );

  @override
  Future<IdentityVault> crateApiIdentityUpdateLinkLabel({
    required String url,
    required String newLabel,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(newLabel, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_vault,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityUpdateLinkLabelConstMeta,
        argValues: [url, newLabel],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityUpdateLinkLabelConstMeta =>
      const TaskConstMeta(
        debugName: "update_link_label",
        argNames: ["url", "newLabel"],
      );

  @override
  Future<VerifiedLink> crateApiIdentityVerifiedLinkDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_verified_link,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityVerifiedLinkDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityVerifiedLinkDefaultConstMeta =>
      const TaskConstMeta(debugName: "verified_link_default", argNames: []);

  @override
  Future<bool> crateApiIdentityVerifyDevicePairingToken({
    required String token,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityVerifyDevicePairingTokenConstMeta,
        argValues: [token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityVerifyDevicePairingTokenConstMeta =>
      const TaskConstMeta(
        debugName: "verify_device_pairing_token",
        argNames: ["token"],
      );

  @override
  Future<bool> crateApiIdentityVerifyProofLocally({required String proof}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(proof, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityVerifyProofLocallyConstMeta,
        argValues: [proof],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityVerifyProofLocallyConstMeta =>
      const TaskConstMeta(
        debugName: "verify_proof_locally",
        argNames: ["proof"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DeviceManifest dco_decode_box_autoadd_device_manifest(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_device_manifest(raw);
  }

  @protected
  DeviceManifest dco_decode_device_manifest(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DeviceManifest(
      tenancyMode: dco_decode_String(arr[0]),
      profiles: dco_decode_list_profile_record(arr[1]),
      associatedConsciaId: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  IdentityVault dco_decode_identity_vault(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return IdentityVault(
      did: dco_decode_String(arr[0]),
      secret: dco_decode_String(arr[1]),
      displayName: dco_decode_String(arr[2]),
      avatarUrl: dco_decode_String(arr[3]),
      proofString: dco_decode_String(arr[4]),
      verifiedLinks: dco_decode_list_verified_link(arr[5]),
      oauthLinks: dco_decode_list_o_auth_link(arr[6]),
      nameHistory: dco_decode_list_name_record(arr[7]),
      ingressEnabled: dco_decode_bool(arr[8]),
      egressEnabled: dco_decode_bool(arr[9]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<NameRecord> dco_decode_list_name_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_name_record).toList();
  }

  @protected
  List<OAuthLink> dco_decode_list_o_auth_link(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_o_auth_link).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProfileRecord> dco_decode_list_profile_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_profile_record).toList();
  }

  @protected
  List<VerifiedLink> dco_decode_list_verified_link(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_verified_link).toList();
  }

  @protected
  NameRecord dco_decode_name_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return NameRecord(
      name: dco_decode_String(arr[0]),
      proofString: dco_decode_String(arr[1]),
      verifiedLinks: dco_decode_list_verified_link(arr[2]),
      activeFromMs: dco_decode_i_64(arr[3]),
      retiredAtMs: dco_decode_i_64(arr[4]),
      changeCertificate: dco_decode_String(arr[5]),
    );
  }

  @protected
  OAuthLink dco_decode_o_auth_link(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return OAuthLink(
      provider: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      sub: dco_decode_String(arr[2]),
      bindingProof: dco_decode_String(arr[3]),
      linkedAtMs: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ProfileRecord dco_decode_profile_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ProfileRecord(
      did: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      avatarUrl: dco_decode_String(arr[2]),
      oauthSubs: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VerifiedLink dco_decode_verified_link(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VerifiedLink(
      platformLabel: dco_decode_String(arr[0]),
      url: dco_decode_String(arr[1]),
      isVerified: dco_decode_bool(arr[2]),
      verifiedAtMs: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DeviceManifest sse_decode_box_autoadd_device_manifest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_device_manifest(deserializer));
  }

  @protected
  DeviceManifest sse_decode_device_manifest(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tenancyMode = sse_decode_String(deserializer);
    var var_profiles = sse_decode_list_profile_record(deserializer);
    var var_associatedConsciaId = sse_decode_opt_String(deserializer);
    return DeviceManifest(
      tenancyMode: var_tenancyMode,
      profiles: var_profiles,
      associatedConsciaId: var_associatedConsciaId,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  IdentityVault sse_decode_identity_vault(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_did = sse_decode_String(deserializer);
    var var_secret = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_avatarUrl = sse_decode_String(deserializer);
    var var_proofString = sse_decode_String(deserializer);
    var var_verifiedLinks = sse_decode_list_verified_link(deserializer);
    var var_oauthLinks = sse_decode_list_o_auth_link(deserializer);
    var var_nameHistory = sse_decode_list_name_record(deserializer);
    var var_ingressEnabled = sse_decode_bool(deserializer);
    var var_egressEnabled = sse_decode_bool(deserializer);
    return IdentityVault(
      did: var_did,
      secret: var_secret,
      displayName: var_displayName,
      avatarUrl: var_avatarUrl,
      proofString: var_proofString,
      verifiedLinks: var_verifiedLinks,
      oauthLinks: var_oauthLinks,
      nameHistory: var_nameHistory,
      ingressEnabled: var_ingressEnabled,
      egressEnabled: var_egressEnabled,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<NameRecord> sse_decode_list_name_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NameRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_name_record(deserializer));
    }
    return ans_;
  }

  @protected
  List<OAuthLink> sse_decode_list_o_auth_link(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <OAuthLink>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_o_auth_link(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProfileRecord> sse_decode_list_profile_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProfileRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_profile_record(deserializer));
    }
    return ans_;
  }

  @protected
  List<VerifiedLink> sse_decode_list_verified_link(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VerifiedLink>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_verified_link(deserializer));
    }
    return ans_;
  }

  @protected
  NameRecord sse_decode_name_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_proofString = sse_decode_String(deserializer);
    var var_verifiedLinks = sse_decode_list_verified_link(deserializer);
    var var_activeFromMs = sse_decode_i_64(deserializer);
    var var_retiredAtMs = sse_decode_i_64(deserializer);
    var var_changeCertificate = sse_decode_String(deserializer);
    return NameRecord(
      name: var_name,
      proofString: var_proofString,
      verifiedLinks: var_verifiedLinks,
      activeFromMs: var_activeFromMs,
      retiredAtMs: var_retiredAtMs,
      changeCertificate: var_changeCertificate,
    );
  }

  @protected
  OAuthLink sse_decode_o_auth_link(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_provider = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_sub = sse_decode_String(deserializer);
    var var_bindingProof = sse_decode_String(deserializer);
    var var_linkedAtMs = sse_decode_i_64(deserializer);
    return OAuthLink(
      provider: var_provider,
      displayName: var_displayName,
      sub: var_sub,
      bindingProof: var_bindingProof,
      linkedAtMs: var_linkedAtMs,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProfileRecord sse_decode_profile_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_did = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_avatarUrl = sse_decode_String(deserializer);
    var var_oauthSubs = sse_decode_list_String(deserializer);
    return ProfileRecord(
      did: var_did,
      displayName: var_displayName,
      avatarUrl: var_avatarUrl,
      oauthSubs: var_oauthSubs,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VerifiedLink sse_decode_verified_link(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_platformLabel = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_isVerified = sse_decode_bool(deserializer);
    var var_verifiedAtMs = sse_decode_i_64(deserializer);
    return VerifiedLink(
      platformLabel: var_platformLabel,
      url: var_url,
      isVerified: var_isVerified,
      verifiedAtMs: var_verifiedAtMs,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_device_manifest(
    DeviceManifest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_device_manifest(self, serializer);
  }

  @protected
  void sse_encode_device_manifest(
    DeviceManifest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.tenancyMode, serializer);
    sse_encode_list_profile_record(self.profiles, serializer);
    sse_encode_opt_String(self.associatedConsciaId, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_identity_vault(IdentityVault self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.did, serializer);
    sse_encode_String(self.secret, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.avatarUrl, serializer);
    sse_encode_String(self.proofString, serializer);
    sse_encode_list_verified_link(self.verifiedLinks, serializer);
    sse_encode_list_o_auth_link(self.oauthLinks, serializer);
    sse_encode_list_name_record(self.nameHistory, serializer);
    sse_encode_bool(self.ingressEnabled, serializer);
    sse_encode_bool(self.egressEnabled, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_name_record(
    List<NameRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_name_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_o_auth_link(
    List<OAuthLink> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_o_auth_link(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_profile_record(
    List<ProfileRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_profile_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_verified_link(
    List<VerifiedLink> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_verified_link(item, serializer);
    }
  }

  @protected
  void sse_encode_name_record(NameRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.proofString, serializer);
    sse_encode_list_verified_link(self.verifiedLinks, serializer);
    sse_encode_i_64(self.activeFromMs, serializer);
    sse_encode_i_64(self.retiredAtMs, serializer);
    sse_encode_String(self.changeCertificate, serializer);
  }

  @protected
  void sse_encode_o_auth_link(OAuthLink self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.provider, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.sub, serializer);
    sse_encode_String(self.bindingProof, serializer);
    sse_encode_i_64(self.linkedAtMs, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_profile_record(ProfileRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.did, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.avatarUrl, serializer);
    sse_encode_list_String(self.oauthSubs, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_verified_link(VerifiedLink self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.platformLabel, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_bool(self.isVerified, serializer);
    sse_encode_i_64(self.verifiedAtMs, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
