// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/identity.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DeviceManifest dco_decode_box_autoadd_device_manifest(dynamic raw);

  @protected
  DeviceManifest dco_decode_device_manifest(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IdentityVault dco_decode_identity_vault(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<NameRecord> dco_decode_list_name_record(dynamic raw);

  @protected
  List<OAuthLink> dco_decode_list_o_auth_link(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProfileRecord> dco_decode_list_profile_record(dynamic raw);

  @protected
  List<VerifiedLink> dco_decode_list_verified_link(dynamic raw);

  @protected
  NameRecord dco_decode_name_record(dynamic raw);

  @protected
  OAuthLink dco_decode_o_auth_link(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ProfileRecord dco_decode_profile_record(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VerifiedLink dco_decode_verified_link(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DeviceManifest sse_decode_box_autoadd_device_manifest(
    SseDeserializer deserializer,
  );

  @protected
  DeviceManifest sse_decode_device_manifest(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IdentityVault sse_decode_identity_vault(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<NameRecord> sse_decode_list_name_record(SseDeserializer deserializer);

  @protected
  List<OAuthLink> sse_decode_list_o_auth_link(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProfileRecord> sse_decode_list_profile_record(
    SseDeserializer deserializer,
  );

  @protected
  List<VerifiedLink> sse_decode_list_verified_link(
    SseDeserializer deserializer,
  );

  @protected
  NameRecord sse_decode_name_record(SseDeserializer deserializer);

  @protected
  OAuthLink sse_decode_o_auth_link(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ProfileRecord sse_decode_profile_record(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VerifiedLink sse_decode_verified_link(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_device_manifest(
    DeviceManifest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_manifest(
    DeviceManifest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_identity_vault(IdentityVault self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_name_record(
    List<NameRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_o_auth_link(
    List<OAuthLink> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_profile_record(
    List<ProfileRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_verified_link(
    List<VerifiedLink> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_name_record(NameRecord self, SseSerializer serializer);

  @protected
  void sse_encode_o_auth_link(OAuthLink self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_profile_record(ProfileRecord self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_verified_link(VerifiedLink self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
