// =============================================================================
// lib.rs — Crate Root (Flutter Library Target)
// =============================================================================
//
// This is the library entry point for the Rust crate when compiled as a shared
// library (.so/.dylib/.dll) for Flutter. It is NOT used when building the
// standalone Conscia beacon binary (see main.rs for that).
//
// Key responsibility: Provides a global Tokio runtime singleton. Because FRB
// calls Rust functions from Dart isolates, we need a single long-lived async
// runtime that outlives any individual FFI call. All async functions in the
// `api/` modules execute on this runtime.
// =============================================================================

use tokio::runtime::Runtime;
use once_cell::sync::Lazy;

/// Global Tokio runtime shared by all FRB-bridged async functions.
/// Initialized lazily on first use and lives for the entire app lifetime.
static RUNTIME: Lazy<Runtime> = Lazy::new(|| {
    Runtime::new().expect("Failed to create Tokio runtime")
});

/// Returns a reference to the global Tokio runtime.
pub fn runtime() -> &'static Runtime {
    &*RUNTIME
}

// --- Module declarations ---
pub mod api;              // FRB-scanned public surface (willow, network, simple)
mod frb_generated;        // Auto-generated by `flutter_rust_bridge_codegen generate`
