// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `save_db_to_disk`, `storage_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<bool> initWillowDatabase({
  required String did,
  required String secret,
}) => RustLib.instance.api.crateApiMessagingInitWillowDatabase(
  did: did,
  secret: secret,
);

Future<List<Conversation>> fetchConversations() =>
    RustLib.instance.api.crateApiMessagingFetchConversations();

Future<Message> sendWillowMessage({
  required String conversationId,
  required String authorDid,
  required String content,
}) => RustLib.instance.api.crateApiMessagingSendWillowMessage(
  conversationId: conversationId,
  authorDid: authorDid,
  content: content,
);

Future<List<Message>> getMessagesForConversation({required String convoId}) =>
    RustLib.instance.api.crateApiMessagingGetMessagesForConversation(
      convoId: convoId,
    );

Future<Conversation> createConversation({
  required String title,
  required List<String> peers,
}) => RustLib.instance.api.crateApiMessagingCreateConversation(
  title: title,
  peers: peers,
);

Future<void> deleteConversation({required String convoId}) =>
    RustLib.instance.api.crateApiMessagingDeleteConversation(convoId: convoId);

Future<String> delegateCapability({
  required String delegatorDid,
  required String delegatorSecret,
  required String targetDid,
  required String namespaceId,
  required String level,
}) => RustLib.instance.api.crateApiMessagingDelegateCapability(
  delegatorDid: delegatorDid,
  delegatorSecret: delegatorSecret,
  targetDid: targetDid,
  namespaceId: namespaceId,
  level: level,
);

Future<bool> verifyCapability({required String capJson}) =>
    RustLib.instance.api.crateApiMessagingVerifyCapability(capJson: capJson);

Future<Map<String, String>> getCapabilitiesForNamespace({
  required String namespaceId,
}) => RustLib.instance.api.crateApiMessagingGetCapabilitiesForNamespace(
  namespaceId: namespaceId,
);

class Conversation {
  final String id;
  final String title;
  final List<String> peers;
  final PlatformInt64 lastActive;
  final int unreadCount;
  final String avatar;
  final bool isGroup;

  const Conversation({
    required this.id,
    required this.title,
    required this.peers,
    required this.lastActive,
    required this.unreadCount,
    required this.avatar,
    required this.isGroup,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      peers.hashCode ^
      lastActive.hashCode ^
      unreadCount.hashCode ^
      avatar.hashCode ^
      isGroup.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Conversation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          peers == other.peers &&
          lastActive == other.lastActive &&
          unreadCount == other.unreadCount &&
          avatar == other.avatar &&
          isGroup == other.isGroup;
}

class Message {
  final String id;
  final String conversationId;
  final String authorDid;
  final String content;
  final PlatformInt64 timestampMs;

  const Message({
    required this.id,
    required this.conversationId,
    required this.authorDid,
    required this.content,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      conversationId.hashCode ^
      authorDid.hashCode ^
      content.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Message &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          conversationId == other.conversationId &&
          authorDid == other.authorDid &&
          content == other.content &&
          timestampMs == other.timestampMs;
}
