// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> shutdownNetwork() =>
    RustLib.instance.api.crateApiNetworkShutdownNetwork();

Future<void> startIrohNode({
  required String did,
  required String secretKeyB58,
}) => RustLib.instance.api.crateApiNetworkStartIrohNode(
  did: did,
  secretKeyB58: secretKeyB58,
);

Future<String> getNodeId() => RustLib.instance.api.crateApiNetworkGetNodeId();

Future<String> saveBlob({required List<int> bytes}) =>
    RustLib.instance.api.crateApiNetworkSaveBlob(bytes: bytes);

Future<void> broadcastMessageHash({
  required U8Array32 namespace,
  required String hashStr,
}) => RustLib.instance.api.crateApiNetworkBroadcastMessageHash(
  namespace: namespace,
  hashStr: hashStr,
);

Future<void> joinConversationTopic({required U8Array32 namespace}) => RustLib
    .instance
    .api
    .crateApiNetworkJoinConversationTopic(namespace: namespace);

Future<void> setAssociatedConscia({required String nodeId}) =>
    RustLib.instance.api.crateApiNetworkSetAssociatedConscia(nodeId: nodeId);

Future<void> forceHandshake() =>
    RustLib.instance.api.crateApiNetworkForceHandshake();

Future<ConsciaStatus> getConsciaStatus() =>
    RustLib.instance.api.crateApiNetworkGetConsciaStatus();

Future<List<PeerInfo>> getPeerList() =>
    RustLib.instance.api.crateApiNetworkGetPeerList();

Future<List<String>> getPendingRequests() =>
    RustLib.instance.api.crateApiNetworkGetPendingRequests();

Future<Map<String, String>> getAllCapabilities() =>
    RustLib.instance.api.crateApiNetworkGetAllCapabilities();

Future<void> authorizeNode({required String nodeId, required String role}) =>
    RustLib.instance.api.crateApiNetworkAuthorizeNode(
      nodeId: nodeId,
      role: role,
    );

Future<void> revokeNode({required String nodeId}) =>
    RustLib.instance.api.crateApiNetworkRevokeNode(nodeId: nodeId);

Future<void> requestAccess() =>
    RustLib.instance.api.crateApiNetworkRequestAccess();

class ConsciaStatus {
  final String? nodeId;
  final bool isConnected;
  final int activePeers;

  const ConsciaStatus({
    this.nodeId,
    required this.isConnected,
    required this.activePeers,
  });

  @override
  int get hashCode =>
      nodeId.hashCode ^ isConnected.hashCode ^ activePeers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConsciaStatus &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          isConnected == other.isConnected &&
          activePeers == other.activePeers;
}

class PeerInfo {
  final String nodeId;
  final List<String> addresses;

  const PeerInfo({required this.nodeId, required this.addresses});

  @override
  int get hashCode => nodeId.hashCode ^ addresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerInfo &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          addresses == other.addresses;
}

class U8Array32 extends NonGrowableListView<int> {
  static const arraySize = 32;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array32(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array32.init() : this(Uint8List(arraySize));
}
