// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_true`, `generate_proof_string_for_format`, `get_active_did_internal`, `get_active_identity_sync`, `load_oauth_links`, `save_db_to_disk`, `save_oauth_links`, `storage_path`, `update_device_manifest`, `verify_raw_sig`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProfileMetadata`, `UserIdentity`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<DeviceManifest> getDeviceManifest() =>
    RustLib.instance.api.crateApiWillowGetDeviceManifest();

Future<void> saveDeviceManifest({required DeviceManifest manifest}) =>
    RustLib.instance.api.crateApiWillowSaveDeviceManifest(manifest: manifest);

/// Closes the active databases, unloads identity, and signals network shutdown
Future<void> signOutProfile() =>
    RustLib.instance.api.crateApiWillowSignOutProfile();

/// Sets the given DID as the active profile and boots up its P2P network node.
Future<bool> switchActiveProfile({required String did}) =>
    RustLib.instance.api.crateApiWillowSwitchActiveProfile(did: did);

/// Generates a genuine ed25519 keypair and encodes it into a did:peer identifier
Future<IdentityVault> generateNewIdentity() =>
    RustLib.instance.api.crateApiWillowGenerateNewIdentity();

/// Returns the active node identity. Returns an empty vault if no identity is active.
Future<IdentityVault> getActiveIdentity() =>
    RustLib.instance.api.crateApiWillowGetActiveIdentity();

Future<IdentityVault> updateActiveProfile({
  required String name,
  required String avatar,
}) => RustLib.instance.api.crateApiWillowUpdateActiveProfile(
  name: name,
  avatar: avatar,
);

/// Generates a signed proof string linking the display name to the did:peer key.
/// Format (Legacy): exotalk-proof:v1:did={DID}:name={NAME}:sig={BASE58_SIG}
/// Format (Full Compact): etp1:{PUBKEY_B58}.{SIG_B58}
/// Format (Minimal): ets1:{SIG_B58}
Future<String> generateVerificationProof({required String format}) => RustLib
    .instance
    .api
    .crateApiWillowGenerateVerificationProof(format: format);

/// Evaluates all available proof formats and returns the best one that fits within max_chars.
Future<String> generateBestProof({required BigInt maxChars}) =>
    RustLib.instance.api.crateApiWillowGenerateBestProof(maxChars: maxChars);

/// Verifies any supported ExoTalk proof string locally.
Future<bool> verifyProofLocally({required String proof}) =>
    RustLib.instance.api.crateApiWillowVerifyProofLocally(proof: proof);

Future<IdentityVault> setIngressEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiWillowSetIngressEnabled(enabled: enabled);

Future<IdentityVault> setEgressEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiWillowSetEgressEnabled(enabled: enabled);

/// Adds a pending (unverified) link to the vault.
Future<IdentityVault> addVerificationLink({
  required String label,
  required String url,
}) => RustLib.instance.api.crateApiWillowAddVerificationLink(
  label: label,
  url: url,
);

/// Marks an existing link by URL as verified or failed after an HTTP check.
Future<IdentityVault> confirmVerificationLink({
  required String url,
  required bool verified,
}) => RustLib.instance.api.crateApiWillowConfirmVerificationLink(
  url: url,
  verified: verified,
);

/// Removes a link by URL.
Future<IdentityVault> removeVerificationLink({required String url}) =>
    RustLib.instance.api.crateApiWillowRemoveVerificationLink(url: url);

/// Renames the display label of a link.
Future<IdentityVault> updateLinkLabel({
  required String url,
  required String newLabel,
}) => RustLib.instance.api.crateApiWillowUpdateLinkLabel(
  url: url,
  newLabel: newLabel,
);

/// Returns the full name history list.
Future<List<NameRecord>> getNameHistory() =>
    RustLib.instance.api.crateApiWillowGetNameHistory();

/// Links an OAuth account to the active did:peer by signing a binding proof.
Future<OAuthLink> addOauthLink({
  required String provider,
  required String displayName,
  required String sub,
}) => RustLib.instance.api.crateApiWillowAddOauthLink(
  provider: provider,
  displayName: displayName,
  sub: sub,
);

/// Removes an OAuth link by provider key.
Future<void> removeOauthLink({required String provider}) =>
    RustLib.instance.api.crateApiWillowRemoveOauthLink(provider: provider);

/// Returns all linked OAuth accounts.
Future<List<OAuthLink>> getOauthLinks() =>
    RustLib.instance.api.crateApiWillowGetOauthLinks();

/// Finds the did:peer for a given OAuth provider + sub combination.
/// Returns an empty string if not found.
Future<String> findDidForOauth({
  required String provider,
  required String sub,
}) => RustLib.instance.api.crateApiWillowFindDidForOauth(
  provider: provider,
  sub: sub,
);

/// Generates a short-lived signed pairing token for QR-code device sync.
/// The token encodes: did + timestamp + signature. Expires after 5 minutes.
Future<String> generateDevicePairingToken() =>
    RustLib.instance.api.crateApiWillowGenerateDevicePairingToken();

/// Verifies a pairing token (checks signature and 5-minute expiry).
Future<bool> verifyDevicePairingToken({required String token}) =>
    RustLib.instance.api.crateApiWillowVerifyDevicePairingToken(token: token);

/// Exports the full profile + OAuth links as a JSON string (for cross-device transfer).
/// In a production implementation this would be encrypted; here it is signed.
Future<String> exportProfileBundle() =>
    RustLib.instance.api.crateApiWillowExportProfileBundle();

/// Imports a profile bundle from another device (verifies did:peer signature first).
Future<bool> importProfileBundle({required String bundle}) =>
    RustLib.instance.api.crateApiWillowImportProfileBundle(bundle: bundle);

Future<bool> initWillowDatabase() =>
    RustLib.instance.api.crateApiWillowInitWillowDatabase();

Future<List<Conversation>> fetchConversations() =>
    RustLib.instance.api.crateApiWillowFetchConversations();

Future<Message> sendWillowMessage({
  required String conversationId,
  required String authorDid,
  required String content,
}) => RustLib.instance.api.crateApiWillowSendWillowMessage(
  conversationId: conversationId,
  authorDid: authorDid,
  content: content,
);

Future<List<Message>> getMessagesForConversation({required String convoId}) =>
    RustLib.instance.api.crateApiWillowGetMessagesForConversation(
      convoId: convoId,
    );

Future<Conversation> createConversation({
  required String title,
  required List<String> peers,
}) => RustLib.instance.api.crateApiWillowCreateConversation(
  title: title,
  peers: peers,
);

Future<void> deleteConversation({required String convoId}) =>
    RustLib.instance.api.crateApiWillowDeleteConversation(convoId: convoId);

/// Signs and gossips a new Meadowcap Capability token granting access to a conversation.
/// 💡 MENTOR TIP: "Delegation" means giving someone else the power to speak.
/// We use our private key to sign a specialized payload that only we could
/// have created. When other peers see this token, they'll know the math
/// proves it came from us.
Future<String> delegateCapability({
  required String targetDid,
  required String namespaceId,
  required String level,
}) => RustLib.instance.api.crateApiWillowDelegateCapability(
  targetDid: targetDid,
  namespaceId: namespaceId,
  level: level,
);

/// Verifies a Meadowcap Capability token mathematically against the delegator's active DID
Future<bool> verifyCapability({required String capJson}) =>
    RustLib.instance.api.crateApiWillowVerifyCapability(capJson: capJson);

/// Fetches the current roster of verified peers for a specific conversation.
Future<Map<String, String>> getCapabilitiesForNamespace({
  required String namespaceId,
}) => RustLib.instance.api.crateApiWillowGetCapabilitiesForNamespace(
  namespaceId: namespaceId,
);

Future<String?> findProfileByOauth({
  required String provider,
  required String sub,
}) => RustLib.instance.api.crateApiWillowFindProfileByOauth(
  provider: provider,
  sub: sub,
);

Future<String> createProfileFromOauth({
  required String provider,
  required String sub,
  required String name,
  required String avatar,
}) => RustLib.instance.api.crateApiWillowCreateProfileFromOauth(
  provider: provider,
  sub: sub,
  name: name,
  avatar: avatar,
);

Future<bool> linkOauthToExistingProfile({
  required String did,
  required String provider,
  required String sub,
}) => RustLib.instance.api.crateApiWillowLinkOauthToExistingProfile(
  did: did,
  provider: provider,
  sub: sub,
);

/// Represents a direct or group conversation
class Conversation {
  final String id;
  final String title;
  final List<String> peers;
  final PlatformInt64 lastActive;
  final int unreadCount;
  final String avatar;
  final bool isGroup;

  const Conversation({
    required this.id,
    required this.title,
    required this.peers,
    required this.lastActive,
    required this.unreadCount,
    required this.avatar,
    required this.isGroup,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      peers.hashCode ^
      lastActive.hashCode ^
      unreadCount.hashCode ^
      avatar.hashCode ^
      isGroup.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Conversation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          peers == other.peers &&
          lastActive == other.lastActive &&
          unreadCount == other.unreadCount &&
          avatar == other.avatar &&
          isGroup == other.isGroup;
}

/// Core device settings and manifest of all local profiles.
class DeviceManifest {
  final String tenancyMode;
  final List<ProfileRecord> profiles;
  final String? associatedConsciaId;

  const DeviceManifest({
    required this.tenancyMode,
    required this.profiles,
    this.associatedConsciaId,
  });

  @override
  int get hashCode =>
      tenancyMode.hashCode ^ profiles.hashCode ^ associatedConsciaId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceManifest &&
          runtimeType == other.runtimeType &&
          tenancyMode == other.tenancyMode &&
          profiles == other.profiles &&
          associatedConsciaId == other.associatedConsciaId;
}

/// Represents a loaded Node Identity (Keypair)
class IdentityVault {
  final String did;
  final String secret;
  final String displayName;
  final String avatarUrl;
  final String proofString;
  final List<VerifiedLink> verifiedLinks;
  final List<OAuthLink> oauthLinks;
  final List<NameRecord> nameHistory;
  final bool ingressEnabled;
  final bool egressEnabled;

  const IdentityVault({
    required this.did,
    required this.secret,
    required this.displayName,
    required this.avatarUrl,
    required this.proofString,
    required this.verifiedLinks,
    required this.oauthLinks,
    required this.nameHistory,
    required this.ingressEnabled,
    required this.egressEnabled,
  });

  @override
  int get hashCode =>
      did.hashCode ^
      secret.hashCode ^
      displayName.hashCode ^
      avatarUrl.hashCode ^
      proofString.hashCode ^
      verifiedLinks.hashCode ^
      oauthLinks.hashCode ^
      nameHistory.hashCode ^
      ingressEnabled.hashCode ^
      egressEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityVault &&
          runtimeType == other.runtimeType &&
          did == other.did &&
          secret == other.secret &&
          displayName == other.displayName &&
          avatarUrl == other.avatarUrl &&
          proofString == other.proofString &&
          verifiedLinks == other.verifiedLinks &&
          oauthLinks == other.oauthLinks &&
          nameHistory == other.nameHistory &&
          ingressEnabled == other.ingressEnabled &&
          egressEnabled == other.egressEnabled;
}

/// A cryptographically signed Willow message payload
class Message {
  final String id;
  final String conversationId;
  final String authorDid;
  final String content;
  final PlatformInt64 timestampMs;

  const Message({
    required this.id,
    required this.conversationId,
    required this.authorDid,
    required this.content,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      conversationId.hashCode ^
      authorDid.hashCode ^
      content.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Message &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          conversationId == other.conversationId &&
          authorDid == other.authorDid &&
          content == other.content &&
          timestampMs == other.timestampMs;
}

/// An archived name record kept when the user renames themselves.
class NameRecord {
  final String name;
  final String proofString;
  final List<VerifiedLink> verifiedLinks;
  final PlatformInt64 activeFromMs;
  final PlatformInt64 retiredAtMs;
  final String changeCertificate;

  const NameRecord({
    required this.name,
    required this.proofString,
    required this.verifiedLinks,
    required this.activeFromMs,
    required this.retiredAtMs,
    required this.changeCertificate,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      proofString.hashCode ^
      verifiedLinks.hashCode ^
      activeFromMs.hashCode ^
      retiredAtMs.hashCode ^
      changeCertificate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NameRecord &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          proofString == other.proofString &&
          verifiedLinks == other.verifiedLinks &&
          activeFromMs == other.activeFromMs &&
          retiredAtMs == other.retiredAtMs &&
          changeCertificate == other.changeCertificate;
}

/// An OAuth account linked as a secondary sign-in method.
class OAuthLink {
  final String provider;
  final String displayName;
  final String sub;
  final String bindingProof;
  final PlatformInt64 linkedAtMs;

  const OAuthLink({
    required this.provider,
    required this.displayName,
    required this.sub,
    required this.bindingProof,
    required this.linkedAtMs,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      displayName.hashCode ^
      sub.hashCode ^
      bindingProof.hashCode ^
      linkedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OAuthLink &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          displayName == other.displayName &&
          sub == other.sub &&
          bindingProof == other.bindingProof &&
          linkedAtMs == other.linkedAtMs;
}

class ProfileRecord {
  final String did;
  final String displayName;
  final String avatarUrl;
  final List<String> oauthSubs;

  const ProfileRecord({
    required this.did,
    required this.displayName,
    required this.avatarUrl,
    required this.oauthSubs,
  });

  @override
  int get hashCode =>
      did.hashCode ^
      displayName.hashCode ^
      avatarUrl.hashCode ^
      oauthSubs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileRecord &&
          runtimeType == other.runtimeType &&
          did == other.did &&
          displayName == other.displayName &&
          avatarUrl == other.avatarUrl &&
          oauthSubs == other.oauthSubs;
}

/// An independently-verified link between a did:peer and a public URL.
class VerifiedLink {
  final String platformLabel;
  final String url;
  final bool isVerified;
  final PlatformInt64 verifiedAtMs;

  const VerifiedLink({
    required this.platformLabel,
    required this.url,
    required this.isVerified,
    required this.verifiedAtMs,
  });

  static Future<VerifiedLink> default_() =>
      RustLib.instance.api.crateApiWillowVerifiedLinkDefault();

  @override
  int get hashCode =>
      platformLabel.hashCode ^
      url.hashCode ^
      isVerified.hashCode ^
      verifiedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerifiedLink &&
          runtimeType == other.runtimeType &&
          platformLabel == other.platformLabel &&
          url == other.url &&
          isVerified == other.isVerified &&
          verifiedAtMs == other.verifiedAtMs;
}
