// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/messaging.dart';
import 'api/network.dart';
import 'api/telemetry_server.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -713976098;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_exotalk_flutter',
        ioDirectory: '../exotalk_engine/exotalk_ffi/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiNetworkAuthorizeNode({
    required String nodeId,
    required String role,
  });

  Future<void> crateApiNetworkBroadcastMessageHash({
    required U8Array32 namespace,
    required String hashStr,
  });

  Future<Conversation> crateApiMessagingCreateConversation({
    required String title,
    required List<String> peers,
  });

  Future<String> crateApiMessagingDelegateCapability({
    required String delegatorDid,
    required String delegatorSecret,
    required String targetDid,
    required String namespaceId,
    required String level,
  });

  Future<void> crateApiMessagingDeleteConversation({required String convoId});

  Future<List<Conversation>> crateApiMessagingFetchConversations();

  Future<void> crateApiNetworkForceHandshake();

  Future<Map<String, String>> crateApiNetworkGetAllCapabilities();

  Future<Map<String, String>> crateApiMessagingGetCapabilitiesForNamespace({
    required String namespaceId,
  });

  Future<ConsciaStatus> crateApiNetworkGetConsciaStatus();

  Future<List<Message>> crateApiMessagingGetMessagesForConversation({
    required String convoId,
  });

  Future<String> crateApiNetworkGetNodeId();

  Future<List<PeerInfo>> crateApiNetworkGetPeerList();

  Future<List<String>> crateApiNetworkGetPendingRequests();

  Future<void> crateApiSimpleInitApp();

  Future<bool> crateApiMessagingInitWillowDatabase({
    required String did,
    required String secret,
  });

  Future<void> crateApiNetworkJoinConversationTopic({
    required U8Array32 namespace,
  });

  Future<void> crateApiNetworkRequestAccess();

  Future<void> crateApiNetworkRevokeNode({required String nodeId});

  Future<String> crateApiNetworkSaveBlob({required List<int> bytes});

  Future<Message> crateApiMessagingSendWillowMessage({
    required String conversationId,
    required String authorDid,
    required String content,
  });

  Future<void> crateApiNetworkSetAssociatedConscia({required String nodeId});

  Future<void> crateApiNetworkShutdownNetwork();

  Future<void> crateApiNetworkStartIrohNode({
    required String did,
    required String secretKeyB58,
  });

  Future<void> crateApiTelemetryServerStartTelemetryServer();

  Future<bool> crateApiMessagingVerifyCapability({required String capJson});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiNetworkAuthorizeNode({
    required String nodeId,
    required String role,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          sse_encode_String(role, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkAuthorizeNodeConstMeta,
        argValues: [nodeId, role],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkAuthorizeNodeConstMeta =>
      const TaskConstMeta(
        debugName: "authorize_node",
        argNames: ["nodeId", "role"],
      );

  @override
  Future<void> crateApiNetworkBroadcastMessageHash({
    required U8Array32 namespace,
    required String hashStr,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8_array_32(namespace, serializer);
          sse_encode_String(hashStr, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkBroadcastMessageHashConstMeta,
        argValues: [namespace, hashStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkBroadcastMessageHashConstMeta =>
      const TaskConstMeta(
        debugName: "broadcast_message_hash",
        argNames: ["namespace", "hashStr"],
      );

  @override
  Future<Conversation> crateApiMessagingCreateConversation({
    required String title,
    required List<String> peers,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          sse_encode_list_String(peers, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_conversation,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMessagingCreateConversationConstMeta,
        argValues: [title, peers],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagingCreateConversationConstMeta =>
      const TaskConstMeta(
        debugName: "create_conversation",
        argNames: ["title", "peers"],
      );

  @override
  Future<String> crateApiMessagingDelegateCapability({
    required String delegatorDid,
    required String delegatorSecret,
    required String targetDid,
    required String namespaceId,
    required String level,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(delegatorDid, serializer);
          sse_encode_String(delegatorSecret, serializer);
          sse_encode_String(targetDid, serializer);
          sse_encode_String(namespaceId, serializer);
          sse_encode_String(level, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMessagingDelegateCapabilityConstMeta,
        argValues: [
          delegatorDid,
          delegatorSecret,
          targetDid,
          namespaceId,
          level,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagingDelegateCapabilityConstMeta =>
      const TaskConstMeta(
        debugName: "delegate_capability",
        argNames: [
          "delegatorDid",
          "delegatorSecret",
          "targetDid",
          "namespaceId",
          "level",
        ],
      );

  @override
  Future<void> crateApiMessagingDeleteConversation({required String convoId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(convoId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMessagingDeleteConversationConstMeta,
        argValues: [convoId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagingDeleteConversationConstMeta =>
      const TaskConstMeta(
        debugName: "delete_conversation",
        argNames: ["convoId"],
      );

  @override
  Future<List<Conversation>> crateApiMessagingFetchConversations() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_conversation,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMessagingFetchConversationsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagingFetchConversationsConstMeta =>
      const TaskConstMeta(debugName: "fetch_conversations", argNames: []);

  @override
  Future<void> crateApiNetworkForceHandshake() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkForceHandshakeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkForceHandshakeConstMeta =>
      const TaskConstMeta(debugName: "force_handshake", argNames: []);

  @override
  Future<Map<String, String>> crateApiNetworkGetAllCapabilities() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_Map_String_String_None,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkGetAllCapabilitiesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkGetAllCapabilitiesConstMeta =>
      const TaskConstMeta(debugName: "get_all_capabilities", argNames: []);

  @override
  Future<Map<String, String>> crateApiMessagingGetCapabilitiesForNamespace({
    required String namespaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(namespaceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_Map_String_String_None,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMessagingGetCapabilitiesForNamespaceConstMeta,
        argValues: [namespaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagingGetCapabilitiesForNamespaceConstMeta =>
      const TaskConstMeta(
        debugName: "get_capabilities_for_namespace",
        argNames: ["namespaceId"],
      );

  @override
  Future<ConsciaStatus> crateApiNetworkGetConsciaStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_conscia_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkGetConsciaStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkGetConsciaStatusConstMeta =>
      const TaskConstMeta(debugName: "get_conscia_status", argNames: []);

  @override
  Future<List<Message>> crateApiMessagingGetMessagesForConversation({
    required String convoId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(convoId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_message,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMessagingGetMessagesForConversationConstMeta,
        argValues: [convoId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagingGetMessagesForConversationConstMeta =>
      const TaskConstMeta(
        debugName: "get_messages_for_conversation",
        argNames: ["convoId"],
      );

  @override
  Future<String> crateApiNetworkGetNodeId() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkGetNodeIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkGetNodeIdConstMeta =>
      const TaskConstMeta(debugName: "get_node_id", argNames: []);

  @override
  Future<List<PeerInfo>> crateApiNetworkGetPeerList() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_peer_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkGetPeerListConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkGetPeerListConstMeta =>
      const TaskConstMeta(debugName: "get_peer_list", argNames: []);

  @override
  Future<List<String>> crateApiNetworkGetPendingRequests() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkGetPendingRequestsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkGetPendingRequestsConstMeta =>
      const TaskConstMeta(debugName: "get_pending_requests", argNames: []);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<bool> crateApiMessagingInitWillowDatabase({
    required String did,
    required String secret,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(did, serializer);
          sse_encode_String(secret, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMessagingInitWillowDatabaseConstMeta,
        argValues: [did, secret],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagingInitWillowDatabaseConstMeta =>
      const TaskConstMeta(
        debugName: "init_willow_database",
        argNames: ["did", "secret"],
      );

  @override
  Future<void> crateApiNetworkJoinConversationTopic({
    required U8Array32 namespace,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8_array_32(namespace, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkJoinConversationTopicConstMeta,
        argValues: [namespace],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkJoinConversationTopicConstMeta =>
      const TaskConstMeta(
        debugName: "join_conversation_topic",
        argNames: ["namespace"],
      );

  @override
  Future<void> crateApiNetworkRequestAccess() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkRequestAccessConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkRequestAccessConstMeta =>
      const TaskConstMeta(debugName: "request_access", argNames: []);

  @override
  Future<void> crateApiNetworkRevokeNode({required String nodeId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkRevokeNodeConstMeta,
        argValues: [nodeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkRevokeNodeConstMeta =>
      const TaskConstMeta(debugName: "revoke_node", argNames: ["nodeId"]);

  @override
  Future<String> crateApiNetworkSaveBlob({required List<int> bytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkSaveBlobConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkSaveBlobConstMeta =>
      const TaskConstMeta(debugName: "save_blob", argNames: ["bytes"]);

  @override
  Future<Message> crateApiMessagingSendWillowMessage({
    required String conversationId,
    required String authorDid,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(conversationId, serializer);
          sse_encode_String(authorDid, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_message,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMessagingSendWillowMessageConstMeta,
        argValues: [conversationId, authorDid, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagingSendWillowMessageConstMeta =>
      const TaskConstMeta(
        debugName: "send_willow_message",
        argNames: ["conversationId", "authorDid", "content"],
      );

  @override
  Future<void> crateApiNetworkSetAssociatedConscia({required String nodeId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkSetAssociatedConsciaConstMeta,
        argValues: [nodeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkSetAssociatedConsciaConstMeta =>
      const TaskConstMeta(
        debugName: "set_associated_conscia",
        argNames: ["nodeId"],
      );

  @override
  Future<void> crateApiNetworkShutdownNetwork() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkShutdownNetworkConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkShutdownNetworkConstMeta =>
      const TaskConstMeta(debugName: "shutdown_network", argNames: []);

  @override
  Future<void> crateApiNetworkStartIrohNode({
    required String did,
    required String secretKeyB58,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(did, serializer);
          sse_encode_String(secretKeyB58, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkStartIrohNodeConstMeta,
        argValues: [did, secretKeyB58],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkStartIrohNodeConstMeta =>
      const TaskConstMeta(
        debugName: "start_iroh_node",
        argNames: ["did", "secretKeyB58"],
      );

  @override
  Future<void> crateApiTelemetryServerStartTelemetryServer() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTelemetryServerStartTelemetryServerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTelemetryServerStartTelemetryServerConstMeta =>
      const TaskConstMeta(debugName: "start_telemetry_server", argNames: []);

  @override
  Future<bool> crateApiMessagingVerifyCapability({required String capJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(capJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMessagingVerifyCapabilityConstMeta,
        argValues: [capJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagingVerifyCapabilityConstMeta =>
      const TaskConstMeta(
        debugName: "verify_capability",
        argNames: ["capJson"],
      );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ConsciaStatus dco_decode_conscia_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ConsciaStatus(
      nodeId: dco_decode_opt_String(arr[0]),
      isConnected: dco_decode_bool(arr[1]),
      activePeers: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  Conversation dco_decode_conversation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Conversation(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      peers: dco_decode_list_String(arr[2]),
      lastActive: dco_decode_i_64(arr[3]),
      unreadCount: dco_decode_u_32(arr[4]),
      avatar: dco_decode_String(arr[5]),
      isGroup: dco_decode_bool(arr[6]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Conversation> dco_decode_list_conversation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_conversation).toList();
  }

  @protected
  List<Message> dco_decode_list_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_message).toList();
  }

  @protected
  List<PeerInfo> dco_decode_list_peer_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_peer_info).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  Message dco_decode_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Message(
      id: dco_decode_String(arr[0]),
      conversationId: dco_decode_String(arr[1]),
      authorDid: dco_decode_String(arr[2]),
      content: dco_decode_String(arr[3]),
      timestampMs: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PeerInfo dco_decode_peer_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PeerInfo(
      nodeId: dco_decode_String(arr[0]),
      addresses: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  U8Array32 dco_decode_u_8_array_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array32(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ConsciaStatus sse_decode_conscia_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_opt_String(deserializer);
    var var_isConnected = sse_decode_bool(deserializer);
    var var_activePeers = sse_decode_u_32(deserializer);
    return ConsciaStatus(
      nodeId: var_nodeId,
      isConnected: var_isConnected,
      activePeers: var_activePeers,
    );
  }

  @protected
  Conversation sse_decode_conversation(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_peers = sse_decode_list_String(deserializer);
    var var_lastActive = sse_decode_i_64(deserializer);
    var var_unreadCount = sse_decode_u_32(deserializer);
    var var_avatar = sse_decode_String(deserializer);
    var var_isGroup = sse_decode_bool(deserializer);
    return Conversation(
      id: var_id,
      title: var_title,
      peers: var_peers,
      lastActive: var_lastActive,
      unreadCount: var_unreadCount,
      avatar: var_avatar,
      isGroup: var_isGroup,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Conversation> sse_decode_list_conversation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Conversation>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_conversation(deserializer));
    }
    return ans_;
  }

  @protected
  List<Message> sse_decode_list_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Message>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<PeerInfo> sse_decode_list_peer_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PeerInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_peer_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  Message sse_decode_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_conversationId = sse_decode_String(deserializer);
    var var_authorDid = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_timestampMs = sse_decode_i_64(deserializer);
    return Message(
      id: var_id,
      conversationId: var_conversationId,
      authorDid: var_authorDid,
      content: var_content,
      timestampMs: var_timestampMs,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PeerInfo sse_decode_peer_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_String(deserializer);
    var var_addresses = sse_decode_list_String(deserializer);
    return PeerInfo(nodeId: var_nodeId, addresses: var_addresses);
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  U8Array32 sse_decode_u_8_array_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array32(inner);
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_conscia_status(ConsciaStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.nodeId, serializer);
    sse_encode_bool(self.isConnected, serializer);
    sse_encode_u_32(self.activePeers, serializer);
  }

  @protected
  void sse_encode_conversation(Conversation self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_list_String(self.peers, serializer);
    sse_encode_i_64(self.lastActive, serializer);
    sse_encode_u_32(self.unreadCount, serializer);
    sse_encode_String(self.avatar, serializer);
    sse_encode_bool(self.isGroup, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_conversation(
    List<Conversation> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_conversation(item, serializer);
    }
  }

  @protected
  void sse_encode_list_message(List<Message> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_peer_info(
    List<PeerInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_peer_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_message(Message self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.conversationId, serializer);
    sse_encode_String(self.authorDid, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_i_64(self.timestampMs, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_peer_info(PeerInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nodeId, serializer);
    sse_encode_list_String(self.addresses, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_u_8_array_32(U8Array32 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
