// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 🧠 Educational Context: Moses Breathing Pulse
/// This stream generates a smooth, organic breathing rhythm for the "Sleep" (Yellow) light.
/// By squaring the sine wave, we create a bell-curve effect that lingers at the
/// extremities, mimicking a biological breath instead of a mechanical triangle wave.
Stream<double> breathingPulseStream() =>
    RustLib.instance.api.crateApiBreathingPulseStream();

/// 🧠 Educational Context: Zero-Allocation Health
/// A simple ping-pong to verify the bridge integrity without overhead.
String ping() => RustLib.instance.api.crateApiPing();
